//! Behavioral fidelity: does the Rust port exhibit the same coding behavior as an
//! *independent* Sparsey implementation?
//!
//! Reference = **Sparsey_Alt/Python** (a third-party reimplementation of Rinkus's
//! algorithm from the papers). Its committed fixture is
//! `tests/fixtures/sparsey_alt_reference.json`, generated by
//! `sparsey/fidelity/python/generate_reference.py` (see `ports/sparsey/fidelity/README.md`).
//!
//! Exact codes cannot match across implementations — Sparsey's winner selection is the
//! probabilistic sigmoid CSA, so novel-code assignment is stochastic and RNG-specific
//! (see `doc/AlgorithmTriangulation.md`). What every faithful Sparsey shares are the
//! **behavioral invariants**, which this test asserts hold for BOTH the reference (via
//! the fixture) and our port (run in-process):
//!
//!   1. N well-separated inputs → N *distinct* codes.
//!   2. A learned input, re-presented, *reactivates its own* code (max-V readout).
//!   3. Global familiarity G is high (~1.0) for a learned input, low for a novel one.
//!
//! The fixture is committed, so this runs in CI with no Python/numpy toolchain. It
//! SKIPs (prints a notice, passes) if the fixture is absent.

use std::path::PathBuf;

use serde::Deserialize;
use dcc_sparsey::config::BackoffConfig;
use dcc_sparsey::ids::{MacId, RegionId};
use dcc_sparsey::{NetworkConfigBuilder, Recorder, RegionConfigBuilder, SparseyNet};

const Q: u32 = 5;
const K: u32 = 8;

// Alphabet matches generate_reference.py: 4 well-separated inputs on a 4×4 = 16-cell
// input grid, plus one novel held-out input.
const ALPHABET: &[&[u32]] = &[&[0, 1, 2], &[6, 7, 8], &[11, 12, 13], &[3, 4, 14]];
const NOVEL: &[u32] = &[5, 9, 10, 15];

#[derive(Debug, Deserialize)]
struct Reference {
    invariants: Invariants,
}
#[derive(Debug, Deserialize)]
struct Invariants {
    distinct_codes: usize,
    all_reactivate: bool,
    g_familiar_min: f32,
    g_novel: f32,
}

#[derive(Default)]
struct CaptureRecorder {
    last: Option<(Vec<u32>, f32)>,
}
impl Recorder for CaptureRecorder {
    fn on_code_selected(&mut self, _r: RegionId, _m: MacId, code: &[u32], g: f32, _f: i64) {
        self.last = Some((code.to_vec(), g));
    }
}

fn build_net() -> SparseyNet {
    let cfg = NetworkConfigBuilder::default()
        .region(RegionConfigBuilder::new("input", 0).grid(4, 4).build())
        .region(
            RegionConfigBuilder::new("internal", 1)
                .grid(1, 1)
                .qk(Q, K)
                .persistence(1)
                .backoff(BackoffConfig::canonical(0.9, 0.93, 0.96))
                .build(),
        )
        .connect("input", "internal")
        .build();
    SparseyNet::build(cfg, 42).expect("build behavioral net")
}

/// What one behavioural run produces: the codes learned, the codes recognition
/// returned, the familiarity `G` per recognized input, and `G` for the novel input.
///
/// Named rather than written inline because a four-element tuple says nothing about
/// which `Vec<Vec<u32>>` is which at the call site.
type PortRun = (Vec<Vec<u32>>, Vec<Vec<u32>>, Vec<f32>, f32);

/// Learn the alphabet, finalize, then recognize each input + a novel input.
fn run_port() -> PortRun {
    let mut net = build_net();
    let input = net.region_id("input").unwrap();

    let mut learned = Vec::new();
    for feats in ALPHABET {
        net.set_input(input, feats).unwrap();
        let mut rec = CaptureRecorder::default();
        net.do_frame_learn_rec(&mut rec);
        learned.push(rec.last.clone().expect("code during learn").0);
    }
    net.finalize_learning();
    net.prepare_for_new_run(false);

    let mut recog = Vec::new();
    let mut g_fam = Vec::new();
    for feats in ALPHABET {
        net.set_input(input, feats).unwrap();
        let mut rec = CaptureRecorder::default();
        net.do_frame_recognize_rec(&mut rec);
        let (code, g) = rec.last.clone().expect("code during recognize");
        recog.push(code);
        g_fam.push(g);
    }
    net.set_input(input, NOVEL).unwrap();
    let mut rec = CaptureRecorder::default();
    net.do_frame_recognize_rec(&mut rec);
    let g_novel = rec.last.map(|(_, g)| g).unwrap_or(0.0);

    (learned, recog, g_fam, g_novel)
}

fn distinct(codes: &[Vec<u32>]) -> usize {
    let mut seen: Vec<&Vec<u32>> = Vec::new();
    for c in codes {
        if !seen.contains(&c) {
            seen.push(c);
        }
    }
    seen.len()
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/sparsey_alt_reference.json")
}

#[test]
fn matches_independent_reference_invariants() {
    let path = fixture_path();
    let Ok(s) = std::fs::read_to_string(&path) else {
        eprintln!(
            "SKIP matches_independent_reference_invariants: {} absent.\n\
             Regenerate with sparsey/fidelity/python/generate_reference.py.",
            path.display()
        );
        return;
    };
    let reference: Reference = serde_json::from_str(&s).expect("valid reference fixture");
    let inv = &reference.invariants;

    // The reference itself must exhibit the invariants (guards a bad fixture).
    assert_eq!(inv.distinct_codes, ALPHABET.len(), "reference should separate all inputs");
    assert!(inv.all_reactivate, "reference should reactivate learned codes");
    assert!(inv.g_familiar_min > inv.g_novel, "reference G should separate familiar from novel");

    // Our port, run in-process, must exhibit the SAME invariants.
    let (learned, recog, g_fam, g_novel) = run_port();

    // 1. N distinct inputs → N distinct codes (same count as the reference).
    assert_eq!(
        distinct(&learned),
        inv.distinct_codes,
        "port distinct-code count {} != reference {} (codes {:?})",
        distinct(&learned),
        inv.distinct_codes,
        learned,
    );

    // 2. Every learned input reactivates its own code on recognition.
    let all_reactivate = learned.iter().zip(&recog).all(|(l, r)| l == r);
    assert!(
        all_reactivate,
        "port must reactivate learned codes: learned {learned:?} vs recog {recog:?}",
    );

    // 3. G high for familiar, low for novel — same qualitative ordering as the reference.
    let g_fam_min = g_fam.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(
        g_fam_min >= 0.99,
        "port G for familiar inputs should be ~1.0, got min {g_fam_min}",
    );
    assert!(
        g_novel < g_fam_min,
        "port G_novel ({g_novel}) should be below G_familiar_min ({g_fam_min})",
    );
}

/// Determinism guard for the port scenario.
#[test]
fn port_scenario_is_deterministic() {
    let (l1, r1, _, _) = run_port();
    let (l2, r2, _, _) = run_port();
    assert_eq!(l1, l2, "learn codes must be reproducible");
    assert_eq!(r1, r2, "recognition codes must be reproducible");
}
